trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Container Journey

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: "2.16.3"

- bash: |
    curl $SCRIPT > script.sh
    chmod +x ./script.sh
    commitId=$(Build.SourceVersion)
    commitId=$(echo "${commitId:0:7}")
    echo "./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) hldCommitId $commitId p3 $(Build.BuildId)"
    ./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) hldCommitId $commitId p3 $(Build.BuildId)
  displayName: Update manifest pipeline details in CJ db
  env:
    SCRIPT: https://raw.githubusercontent.com/samiyaakhtar/spk/686-simply-pipelines/scripts/update_introspection.sh


# - bash: |
#     git clone https://github.com/samiyaakhtar/container-journey.git
#     cd container-journey/pipeline-scripts

#     sudo /usr/bin/easy_install virtualenv
#     pip install virtualenv 
#     pip install --upgrade pip
#     python -m virtualenv venv
#     source venv/bin/activate
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt

#     commitId=$(Build.SourceVersion)
#     commitId=$(echo "${commitId:0:7}")
#     echo "python update_pipeline.py $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) hldCommitId $commitId p3 $(Build.BuildId)"
#     python update_pipeline.py $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) hldCommitId $commitId p3 $(Build.BuildId)
#   displayName: Update manifest pipeline details in CJ db

- task: ShellScript@2
  displayName: Validate fabrikate definitions
  inputs:
    scriptPath: build.sh
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    VERIFY_ONLY: 1

- task: ShellScript@2
  displayName: Transform fabrikate definitions and publish to YAML manifests to repo
  inputs:
    scriptPath: build.sh
  condition: ne(variables['Build.Reason'], 'PullRequest')
  env:
    ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN)
    COMMIT_MESSAGE: $(Build.SourceVersionMessage)
    REPO: $(MANIFEST_REPO)
    BRANCH_NAME: $(Build.SourceBranchName)
    HLD_PATH: https://github.com/samiyaakhtar/hello-bedrock-cluster
    
# - script: |
#     cd "$HOME"
#     cd hello-bedrock-manifest
#     latest_commit=$(git rev-parse --short HEAD)
#     cd ../container-journey/pipeline-scripts
#     source venv/bin/activate
#     echo "python update_pipeline.py $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p3 $(Build.BuildId) manifestCommitId $latest_commit"
#     python update_pipeline.py $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p3 $(Build.BuildId) manifestCommitId $latest_commit
#   displayName: Update commit id in database

- script: |
    cd "$HOME"/hello-bedrock-manifest
    curl $SCRIPT > script.sh
    chmod +x ./script.sh
    latest_commit=$(git rev-parse --short HEAD)
    ./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p3 $(Build.BuildId) manifestCommitId $latest_commit
  displayName: Update commit id in database
  env:
    SCRIPT: https://raw.githubusercontent.com/samiyaakhtar/spk/686-simply-pipelines/scripts/update_introspection.sh

